### ISSUE TITLE
(high to some, low to others :-) user experience on alt page on mobile or low vision settings

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-easy-checks#212] opened 2023-12-13 02:51 UTC
See [screencast](https://w3c.zoom.us/rec/share/EwGcIttf7TRswZP1r97Rw5pXMIluedxYUEAVIMcYleyv8Lzp9LXV91cTDgH0lmTz.ejTwFhA-7GB58w0x?startTime=1702434825000)
_Passcode:_ 3*Nqt@GR

Note:
* when "Simply click on the link below:", don't see anything
* odd wrapping makes it nearly impossible to associate the right text with the right image

Some of this is inevitable, and hopefully most users will know to scroll.

Some can and should be fixed. e.g., much smaller images with better line breaks

_(sidenote: mouse pointer is much larger and darker in real life than this screencast shows)_

**Comment by iadawn** [comment] 2023-12-13 10:46
Not much to be done if people don't scroll.

Need more specifics on the 'some can and should be fixed'

**Comment by shawna-slh** [comment] 2023-12-14 20:52
> e.g., much smaller images with better line breaks

**Comment by iadawn** [comment] 2023-12-15 09:49
Wrapping isn't something that there is a huge control over. It will depend on lots of factors as you know.

I can resize the images, but no guarantee that the wrapping will be perfect everywhere.

> Some can and should be fixed

Implies that there are more than just the one example you provided. Hence why I asked for more specifics.

**Comment by iadawn** [comment] 2024-01-11 12:35
Trying to reproduce this is proving difficult as I am not sure what you have done to your page to increase the size. Using the browser zoom or increasing the base font size do not illicit the same behaviour. It looks like your font size is changing but the image size is not... I have not been able to replicate that.

**Comment by iadawn** [comment] 2024-05-03 11:59
Closing but if there are more specifics, please do reopen and add

**Closed by iadawn** 2024-05-03 11:59 UTC
